## https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event
class_name AnalyticsEvent

const ADD_PAYMENT_INFO = "add_payment_info"
const ADD_SHIPPING_INFO = "add_shipping_info"
const ADD_TO_CART = "add_to_cart"
const ADD_TO_WISHLIST = "add_to_wishlist"
const AD_IMPRESSION = "ad_impression"
const APP_OPEN = "app_open"
const BEGIN_CHECKOUT = "begin_checkout"
const CAMPAIGN_DETAILS = "campaign_details"
const EARN_VIRTUAL_CURRENCY = "earn_virtual_currency"
const GENERATE_LEAD = "generate_lead"
const LEVEL_END = "level_end"
const LEVEL_START = "level_start"
const LEVEL_UP = "level_up"
const LOGIN = "login"
const POST_SCORE = "post_score"
const PURCHASE = "purchase"
const REFUND = "refund"
const REMOVE_FROM_CART = "remove_from_cart"
const SCREEN_VIEW = "screen_view"
const SEARCH = "search"
const SELECT_CONTENT = "select_content"
const SELECT_ITEM = "select_item"
const SELECT_PROMOTION = "select_promotion"
const SHARE = "share"
const SIGN_UP = "sign_up"
const SPEND_VIRTUAL_CURRENCY = "spend_virtual_currency"
const TUTORIAL_BEGIN = "tutorial_begin"
const TUTORIAL_COMPLETE = "tutorial_complete"
const UNLOCK_ACHIEVEMENT = "unlock_achievement"
const VIEW_CART = "view_cart"
const VIEW_ITEM = "view_item"
const VIEW_ITEM_LIST = "view_item_list"
const VIEW_PROMOTION = "view_promotion"
const VIEW_SEARCH_RESULTS = "view_search_results"
