class_name AdmobError

const ERROR_CODE_INTERNAL_ERROR = 0
const ERROR_CODE_INVALID_REQUEST = 1
const ERROR_CODE_NETWORK_ERROR = 2
const ERROR_CODE_NO_FILL = 3
const ERROR_CODE_APP_ID_MISSING = 8
const ERROR_CODE_MEDIATION_NO_FILL = 9
const ERROR_CODE_REQUEST_ID_MISMATCH = 10
const ERROR_CODE_INVALID_AD_STRING = 11
