name: Itch.io Deploy Workflow

env:
  GODOT_VERSION: 4.2
  ITCHIO_LINK: "https://adityarahmanda.itch.io/hop-up-bunny"
  EXPORT_NAME: "hopupbunny"

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  itchio:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2
    steps:
      - name: Install Packages
        run: |          
          apt-get update -y
          apt-get install -y rsync
          apt-get install -y curl
      - name: Checkout
        uses: actions/checkout@v3
      - name: Import Godot Assets
        run: |
          godot --headless --verbose --editor --quit
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p ./build/web
          godot -v --headless --export-release "Web" ./build/web/index.html
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
      - name: Deploy Web
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: hop-up-bunny
          ITCH_USER: adityarahmanda
          PACKAGE: build/web
      - name: Send Discord Notification
        run: |
          DISCORD_MESSAGE="Web Build for Rabbit Jump is now live! \nLink: ${ITCHIO_LINK}"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$DISCORD_MESSAGE\"}" ${{ secrets.WEBHOOK_URL }}
      - name: Send Failed Discord Notification
        if: failure()
        run: |
          DISCORD_MESSAGE="Web Build for Rabbit Jump is failed! :smiling_face_with_tear:"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$DISCORD_MESSAGE\"}" ${{ secrets.WEBHOOK_URL }}
