name: Itch.io Deploy Workflow

env:
  GODOT_VERSION: 4.2
  ITCHIO_LINK: "https://adityarahmanda.itch.io/hop-up-bunny"
  EXPORT_NAME: "hopupbunny"

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  itchio:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2
    steps:
      - name: Install Packages
        run: |          
          apt-get update -y
          apt-get install -y rsync
          apt-get install -y curl
      - name: Checkout
        uses: actions/checkout@v3
      - name: Import Godot Assets
        run: |
          godot --headless --verbose --editor --quit
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p ./build/web
          godot -v --headless --export-debug "Web" ./build/web/index.html
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
      - name: Deploy Web
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: hop-up-bunny
          ITCH_USER: adityarahmanda
          PACKAGE: build/web
      - name: Send Discord Notification
        run: |
          DISCORD_MESSAGE="Web Build for Rabbit Jump is now live! \nLink: ${ITCHIO_LINK}"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$DISCORD_MESSAGE\"}" ${{ secrets.WEBHOOK_URL }}
      - name: Send Failed Discord Notification
        if: failure()
        run: |
          DISCORD_MESSAGE="Web Build for Rabbit Jump is failed! :smiling_face_with_tear:"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$DISCORD_MESSAGE\"}" ${{ secrets.WEBHOOK_URL }}
  android:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2
    steps:
      - name: Install Packages
        run: |          
          apt-get update -y
          apt-get install -y rsync
          apt-get install -y curl
          apt-get install -y android-sdk
          apt-get install -y unzip
          sdkmanager --sdk_root="/usr/lib/android-sdk" "platform-tools" "build-tools;33.0.2" "platforms;android-33" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17.0.11+9'
      - name: Import Godot Assets
        run: |
          godot --headless --verbose --editor --quit
      - name: Setup Export Template
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Setup Gradle Build
        run: |
          mkdir -v -p /root/android/build
          unzip ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/android_source.zip -d /root/android/build
          yes | cp -rf ./android/build/* /root/android/build && rm -R ./android/build/*
          mv /root/android/build ./android
      - name: Setup Debug Keystore
        run: |
          echo ${{ vars.SECRET_DEBUG_KEYSTORE_BASE64 }} | base64 --decode > /root/debug.keystore
          echo 'keystore/debug="/root/debug.keystore"' >> export_presets.cfg
          echo 'keystore/debug_user="androiddebugkey"' >> export_presets.cfg
          echo 'keystore/debug_password="android"' >> export_presets.cfg
      - name: Setup SDK Path
        run: |
          echo 'export/android/android_sdk_path = "/usr/lib/android-sdk"' >> /root/.config/godot/editor_settings-4.tres
      - name: Android Build
        run: |
          mkdir -v -p ./build/android
          godot -v --headless --debug --export-debug "Android" ./build/android/${EXPORT_NAME}.apk
          godot -v --headless --debug --export-debug "Android" ./build/android/${EXPORT_NAME}.apk
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/android
      - name: Deploy Android
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: android
          ITCH_GAME: hop-up-bunny
          ITCH_USER: adityarahmanda
          PACKAGE: build/android/${{ env.EXPORT_NAME }}.apk
      - name: Send Discord Notification
        run: |
          DISCORD_MESSAGE="Android Build for Rabbit Jump is now live! \nLink: ${ITCHIO_LINK}"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$DISCORD_MESSAGE\"}" ${{ secrets.WEBHOOK_URL }}
      - name: Send Failed Discord Notification
        if: failure()
        run: |
          DISCORD_MESSAGE="Android Build for Rabbit Jump is failed! :smiling_face_with_tear:"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$DISCORD_MESSAGE\"}" ${{ secrets.WEBHOOK_URL }}
