name: Itch.io Deploy Workflow

env:
  GODOT_VERSION: 4.1.3
  ITCHIO_LINK: "https://adityarahmanda.itch.io/rabvanture-godot"

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  itchio-deploy:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Install Packages
        run: |
          apt-get update -y
          apt-get install -y rsync
          apt-get install -y curl
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          cd /root/
          ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
