name: Itch.io Deploy Workflow

env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: rabvanture

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  itchio-deploy:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Install Packages
        run: |
          apt-get update -y
          apt-get install -y mesa-vulkan-drivers
          apt-get install -y rsync
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p ./build/web
          godot -v --rendering-driver vulkan --export-release "Web" ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Deploy
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: rabvanture-godot
          ITCH_USER: adityarahmanda
          PACKAGE: build/web
