name: Itch.io Deploy Workflow

env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: rabvanture

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  # job id, can be anything
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Deploy To Itch.io
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - name: export game
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
    - name: Deploy
      uses: josephbmanley/butler-publish-itchio-action@v1.0.3
      env:
        BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
        CHANNEL: HTML
        ITCH_GAME: rabvanture-godot
        ITCH_USER: adityarahmanda
        PACKAGE: ${{ steps.export.outputs.archive_directory }}/Web.zip
