name: Itch.io Deploy Workflow

env:
  GODOT_VERSION: 4.1.3
  ITCHIO_LINK: "https://adityarahmanda.itch.io/rabvanture-godot"
  EXPORT_NAME: "rabbitjump"

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  itchio-deploy:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Install Packages
        run: |          
          apt-get update -y
          apt-get install -y rsync
          apt-get install -y curl
          apt-get install -y android-sdk
          sdkmanager --sdk_root="/usr/lib/android-sdk" "platform-tools" "build-tools;33.0.2" "platforms;android-33" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          echo "Setting up godot export template ====================================="
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          echo "Reimporting godot and creating build folder =========================="
          mkdir -v -p ./build/web
          mkdir -v -p ./build/android
          godot -v --headless --export-debug "Web" ./build/web/index.html
          echo "Log variables ========================================================"
          echo ${{ vars.SECRET_RELEASE_KEYSTORE_BASE64 }}
          echo ${{ vars.SECRET_RELEASE_KEYSTORE_USER }}
          echo ${{ vars.SECRET_RELEASE_KEYSTORE_PASSWORD }}
          echo "Setting up android keystores =================================="
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -deststoretype pkcs12
          echo 'keystore/debug="debug.keystore"' >> export_presets.cfg
          echo 'keystore/debug_user="androiddebugkey"' >> export_presets.cfg
          echo 'keystore/debug_password="android"' >> export_presets.cfg
          echo ${{ vars.SECRET_RELEASE_KEYSTORE_BASE64 }} | base64 --decode > release.keystore
          echo 'keystore/release="release.keystore"' >> export_presets.cfg
          echo 'keystore/release_user="${{ vars.SECRET_RELEASE_KEYSTORE_USER }}"' >> export_presets.cfg
          echo 'keystore/release_password="${{ vars.SECRET_RELEASE_KEYSTORE_PASSWORD }}"' >> export_presets.cfg
          cat export_presets.cfg
          echo "Setting up android sdk path =========================================="
          echo 'export/android/android_sdk_path = "/usr/lib/android-sdk"' >> ~/.config/godot/editor_settings-4.tres
          cat ~/.config/godot/editor_settings-4.tres
      - name: Web Build
        run: |
          godot -v --headless --export-debug "Web" ./build/web/index.html
      - name: Android Debug Build
        run: |
          godot -v --headless --debug --export-debug "Android" ./build/android-debug/${EXPORT_NAME}.apk
      - name: Android Release Build
        run: |
          godot -v --headless --export-release "Android" ./build/android-release/${EXPORT_NAME}.apk
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
      - name: Upload Android Debug Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-debug
          path: build/android-debug
      - name: Upload Android Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: build/android-release
      - name: Deploy Web
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: rabvanture-godot
          ITCH_USER: adityarahmanda
          PACKAGE: build/web
      - name: Deploy Android
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: android
          ITCH_GAME: rabvanture-godot
          ITCH_USER: adityarahmanda
          PACKAGE: build/android
      - name: Send Discord Notification
        run: |
          DISCORD_MESSAGE="Build for Rabbit Jump is now live! \nLink: ${ITCHIO_LINK}"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$DISCORD_MESSAGE\"}" ${{ secrets.WEBHOOK_URL }}
      - name: Send Failed Discord Notification
        if: failure()
        run: |
          DISCORD_MESSAGE="Build for Rabbit Jump is failed! :smiling_face_with_tear:"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$DISCORD_MESSAGE\"}" ${{ secrets.WEBHOOK_URL }}
