name: Itch.io Deploy Workflow

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  itchio-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'npm'
          cache-dependency-path: tic-tac-toe-project/yarn.lock
        env:
          CI: true

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: yarn build
        run: yarn build
        env:
          CI: true

      - run: ls

      - name: Deploy
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: rabvanture-godot
          ITCH_USER: adityarahmanda
          PACKAGE: dist
