name: Itch.io Deploy Workflow

env:
  GODOT_VERSION: 4.1.3
  ITCHIO_LINK: "https://adityarahmanda.itch.io/rabvanture-godot"

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  itchio-deploy:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Install Packages
        run: |          
          apt-get update -y
          apt-get install -y rsync
          apt-get install -y curl
          apt-get install -y android-sdk
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Setup Godot
        run: |
          mkdir -v -p ./build/web
          mkdir -v -p ./build/android
          godot -v --headless --export-debug "Web" ./build/web/index.html
      - name: Web Build
        run: |
          godot -v --headless --export-debug "Web" ./build/web/index.html
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
      - name: Deploy Web
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: rabvanture-godot
          ITCH_USER: adityarahmanda
          PACKAGE: build/web
      - name: Android Build
        run: |
          echo $SECRET_DEBUG_KEYSTORE_BASE64 | base64 --decode > /root/release.keystore
          sed 's@keystore/release=".*"@keystore/release="'/root/release.keystore'"@g' -i export_presets.cfg
          sed 's@keystore/release_user=".*"@keystore/release_user="'$SECRET_DEBUG_KEYSTORE_USER'"@g' -i export_presets.cfg
          sed 's@keystore/release_password=".*"@keystore/release_password="'$SECRET_DEBUG_KEYSTORE_PASSWORD'"@g' -i export_presets.cfg
          cat export_presets.cfg
          sdkmanager --sdk_root="/usr/lib/android-sdk" "platform-tools" "build-tools;33.0.2" "platforms;android-33" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"
          sed 's|export/android/android_sdk_path = ".*"|export/android/android_sdk_path = "'/usr/lib/android-sdk'"|g' -i /root/.config/godot/editor_settings-4.tres
mkdir -v -p ~/.config/godot
          cp -v /root/.config/godot/editor_settings-4.tres ~/.config/godot/
          cat ~/.config/godot/editor_settings-4.tres
          godot -v --headless --export-release "Android" ./build/android/index.apk
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/android
      - name: Deploy Android
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: android
          ITCH_GAME: rabvanture-godot
          ITCH_USER: adityarahmanda
          PACKAGE: build/android
      - name: Send Discord Notification
        run: |
          DISCORD_MESSAGE="Build for Rabbit Jump is now live! \nLink: ${ITCHIO_LINK}"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$DISCORD_MESSAGE\"}" ${{ secrets.WEBHOOK_URL }}
      - name: Send Failed Discord Notification
        if: failure()
        run: |
          DISCORD_MESSAGE="Build for Rabbit Jump is failed! :smiling_face_with_tear:"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$DISCORD_MESSAGE\"}" ${{ secrets.WEBHOOK_URL }}
